### ISSUE TITLE
Undefined function or variable 'multigradient'

### ISSUE THREAD

**Issue by athifm** [lrkrol/SEREEGA#11]
MATLAB version R2019a - When the source projection is plotted using, plot_source_projection(source, lf, 'orientation', [1 0 0], 'orientedonly', 1); the following error is thrown.

Error in plot_source_projection (line 70)
addParameter(p, 'colormap', multigradient('preset', 'div.km.BuRd', 'length', 1000), @isnumeric);

**Comment by athifm** [comment]
Fixed the issue and created a pull request https://github.com/lrkrol/SEREEGA/pull/12/commits/a1b7a89c36937760cc71c06c55d947f4f8e0b8e3

**Comment by lrkrol** [comment]
Thanks! I was working with a local version simply called `multigradient`, not `utl_multigradient`, which is why I didn't catch this. I now found the same issue in `plot_component_projection`.

Could you make a little note of your change in the file's own changelog as well, before I merge?

**Comment by athifbu** [comment]
> Thanks! I was working with a local version simply called `multigradient`, not `utl_multigradient`, which is why I didn't catch this. I now found the same issue in `plot_component_projection`.
> 
> Could you make a little note of your change in the file's own changelog as well, before I merge?
Done!

**Comment by athifm** [comment]
> Thanks! I was working with a local version simply called `multigradient`, not `utl_multigradient`, which is why I didn't catch this. I now found the same issue in `plot_component_projection`.
> 
> Could you make a little note of your change in the file's own changelog as well, before I merge?

Done!

**Comment by lrkrol** [comment]
That should do it; thanks again!
