### ISSUE TITLE
Understanding the MNI coordinates

### ISSUE THREAD

**Issue by aline-fidencio** [lrkrol/SEREEGA#19]
Hi!

Thanks for this tool! Looking forward to using it :D 

I have a basic question as I try to understand how to work with SEREEGA. I am trying to define the MNI coordinates at specific Broadmann areas and, for this, I am trying to use tools like MRIcron and https://bioimagesuiteweb.github.io/webapp/mni2tal.html.

Now, just for a double check, I used the MNI coordinates taken from utl_get_component_fromtemplate.m while defining the example 'visual_b135_erp': [-10, -88, 6]. It says it is projecting from BA 18. But when I use this coordinate in MRIcron, it returns BA 17, not BA 18 (see attachment). So I am not sure what I am missing and I just want to make sure I could, for example, use the BioImagesuite to select the BA 24 and use the given MNI coordinates in SEREEGA and that would in fact be the desired BA 24 and not other area. 

Thanks in advance!
Aline

![mricron](https://user-images.githubusercontent.com/22963640/204292377-bd66cb3f-98fb-4e48-98f9-beb1f224fc42.PNG)

**Comment by lrkrol** [comment]
I apologise for my delayed response, but I was wrapping up the [most recent release](https://github.com/lrkrol/SEREEGA/releases/v1.5.0/), which may help to address your issue.

One downside of SEREEGA supporting a multitude of external head models and lead fields is that these may all use different units and coordinate systems. SEREEGA does indeed expect MNI, but this cannot entirely be enforced. And even so, anatomical differences between the models, as well as differences between the various atlases that map coordinates to regions, such as the tool you are using, may both result in the kinds of inaccuracies you see.

The `utl_get_component_fromtemplate` is a function to be used with care. As is also mentioned in the documentation, the components contained there have most likely been defined for different purposes and different models, so the results may not quite translate to your current use case.

That said, of course it is important to be able to locate sources in specific regions of the brain. To that end, SEREEGA now supports atlases, where available. Please have a look if this functionality can solve your problem. You can check if the pre-packaged atlas of e.g. the recently updated New York Head already contains the region you are looking for, or you can add another atlas if this better suits your purposes. For example, the Juelich Histological Atlas supported by `lf_add_atlas_frommni2atlas` contains the region `Brain_GM_Visual_cortex_V2_BA18`, which appears to be the one you are interested in. Do note that the accuracy of these atlases can vary, and that mni2atlas uses a different license than SEREEGA.

**Comment by aline-fidencio** [comment]
Hi Laurens,

nothing to apologize for. It is really great that you take the time to answer. I already played a bit with the new release and the new feature will for sure be really helpful. Thanks a lot! About the template, I just wanted to say that, I have seen your comment somewhere else also saying that we should use the templates with care. I do keep that in mind and I just wanted to say, please still let the templates in SEREEGA. They are very helpful to get started ;)
