### ISSUE TITLE
I can't save my sereega dataset after following the coding tutorial

### ISSUE THREAD

**Issue by Ojayedwards** [lrkrol/SEREEGA#6]
I wrote the  code to simulate EEG data on  sereega from a Matlab script and scalp data is generated and the 64 channel EEG is plotted... 
I've been attempting to save the data in .set format so that I can import it to eeglab but I don't know how to do that..

**Comment by lrkrol** [comment]
To save simulated data as a .set, first convert it into EEGLAB format, using e.g. `utl_create_eeglabdataset`. In the tutorial, we called this dataset `EEG` as per EEGLAB convention. Once it is in EEGLAB format, you can use EEGLAB's own commands to save the data, that is:

`pop_saveset(EEG);` to use the GUI, or 
`pop_saveset(EEG, 'D:\Path\Filename.set')` to save it as a file directly.

Another way is to use EEGLAB's GUI from the main menu. EEGLAB uses the variable `EEG` internally to refer to the currently active dataset. Therefore, if you have assigned the dataset to the variable `EEG`, calling `eeglab redraw` redraws the main menu and recognies the newly created `EEG` as an active dataset. You can then save the dataset from the File menu.

I have updated the tutorial to include this information.
