### ISSUE TITLE
Undefined function or variable 'readlocs'.

### ISSUE THREAD

**Issue by Wale019** [lrkrol/SEREEGA#9]
am new to sereega and i want to run my first simulation script then i keep getting this error

Undefined function or variable 'readlocs'.

Error in lf_generate_fromnyhead (line 108)
lf.chanlocs = readlocs('chanlocs-nyhead231.elp');

**Comment by lrkrol** [comment]
For anyone coming here in future and wondering: this was probably due to EEGLAB not having been started beforehand. :)
